import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer";
import { Header } from "../components/Header";
import Main from "../components/main/Main";

export default function Home() {
  return (
    <div className={styles.container}>
      <Header />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />

      <Footer />
    </div>
  );
}
